---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mailout.fullname" . }}
  labels:
    {{- include "mailout.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth_flat_file.ini: |
    [core]
    methods=PLAIN,LOGIN,CRAM-MD5

    [users]
    {{ .Values.config.auth.username }}={{ .Values.config.auth.password }}
  smtp_smarthost.ini: |
    host={{ .Values.config.smtp_smarthost.host }}
    port={{ .Values.config.smtp_smarthost.port }}
    auth_type={{ .Values.config.smtp_smarthost.auth_type }}
    auth_user={{ .Values.config.smtp_smarthost.auth_user }}
    auth_pass={{ .Values.config.smtp_smarthost.auth_pass }}